controllers:
  resource:
    path: ../../src/Controller/
    namespace: App\Controller
  type: attribute

Kernel:
  resource: App\Kernel
  type: attribute

user_create:
  path: /users/create
  controller: App\Controller\UserController::user_create

login:
  path: /login
  controller: App\Controller\SecurityController::login

task_create:
  path: /tasks/create
  controller: App\Controller\TaskController::task_create

task_list:
  path: /tasks/list
  controller: App\Controller\TaskController::task_list